/opt/homebrew/Library/Homebrew/cmd/shellenv.sh: line 18: /bin/ps: Operation not permitted
// POST { text } -> audio/mpeg generated by OpenAI Text-to-Speech
export default async function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  const text = String(req.body?.text || "").trim();
  if (!text) {
    return res.status(400).json({ error: "Missing text" });
  }
  if (text.length > 600) {
    return res.status(400).json({ error: "Text is too long" });
  }

  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    return res.status(500).json({ error: "TTS is not configured" });
  }

  try {
    const response = await fetch("https://api.openai.com/v1/audio/speech", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "gpt-4o-mini-tts",
        voice: "marin",
        input: text,
        instructions: "Speak clearly and naturally at a measured pace for an English language learner.",
        response_format: "mp3",
      }),
    });

    if (!response.ok) {
      console.error("OpenAI TTS request failed:", response.status, await response.text());
      return res.status(502).json({ error: "Speech generation failed" });
    }

    const audio = await response.arrayBuffer();
    res.setHeader("Content-Type", "audio/mpeg");
    res.setHeader("Cache-Control", "no-store");
    return res.send(Buffer.from(audio));
  } catch (error) {
    console.error("OpenAI TTS error:", error);
    return res.status(502).json({ error: "Speech service unavailable" });
  }
}
